### ISSUE TITLE
Current beta fails to launch

### ISSUE THREAD

**Issue by manuq** [flathub/org.godotengine.Godot#196] opened 2024-12-05 18:48 UTC
The beta flatpak that ships 4.4-dev5 fails to launch with:
```
$ flatpak run org.godotengine.Godot//beta 
bwrap: Can't mkdir /app/jdk: Read-only file system
error: ldconfig failed, exit status 256
```

**Comment by wjt** [comment] 2024-12-06 09:59
You can work around this by removing ``runtime/org.freedesktop.Sdk.Extension.openjdk17//24.08``.

The issue is that `/app/jdk` is not created during build on the beta branch's manifest, though it is in the stable branch.

The two seem to be very out of sync: libspeech is only on stable, not beta, and the version of SCons on stable is much newer.

**Comment by wjt** [comment] 2024-12-06 10:16
I am testing a local branch that resyncs the `beta` branch with `master`, except for the newer Godot version.

**Comment by Zishan-Rahman** [comment] 2024-12-06 10:19
I've been meaning to get the beta branch properly up to sync with the stable branch for a while now, but I haven't got round to it yet. If anyone else wants to do this in the meantime, I'm happy for them to do so, but there's a new development build out for Godot 4.4 and I've also been meaning to open a PR here for that, so _that_ might be a good place to finally sort these issues out.

**Comment by wjt** [comment] 2024-12-06 10:26
I will put that into my PR and restart the local build :)

**Comment by Calinou** [comment] 2024-12-11 08:38
- Fixed by https://github.com/flathub/org.godotengine.Godot/pull/198.

**Closed by Calinou** 2024-12-11 08:38 UTC
Labels: bug
