### ISSUE TITLE
ADB and Jarsigner Issue

### ISSUE THREAD

**Issue by LeVoid** [flathub/org.godotengine.Godot#78] opened 2021-07-08 20:53 UTC
I cannot enter jarsigner nor ADB in Editor > Editor Settings > Android. On my old rig I was able to, but now I can't input the path to neither anymore.
![image](https://user-images.githubusercontent.com/71784437/124989182-2566fd00-e03f-11eb-9c1c-2895ca3fc2ff.png)

I really don't know why I can't input them.
Any ideas?

**Comment by Calinou** [comment] 2021-07-08 20:59
Duplicate of https://github.com/flathub/org.godotengine.Godot/issues/63. As a workaround, download a Godot binary from [godotengine.org/download](https://godotengine.org/download) and use it to export to Android;

**Closed by Calinou** 2021-07-08 20:59 UTC

**Comment by LeVoid** [comment] 2021-07-08 21:16
I'm sorry to bother, but I don't know how to do that or what you mean by "binary".

**Comment by Calinou** [comment] 2021-07-08 21:24
> I'm sorry to bother, but I don't know how to do that or what you mean by "binary".

"Godot binary" refers to the Godot editor you can download from that website. It's all explained on the website.

**Comment by LeVoid** [comment] 2021-07-08 22:24
Does not seem to be working.
But meanwhile I stumbled about a different issue which was answered with "Maybe there are illegal characters in one or more of your game files".
The issue in question is: https://godotengine.org/qa/7289/android-app-not-installing

My issue might be related to this issue, because my keyboard likes to keep switching between two languages...
